#map-POINTLM.inc
    MAXSCALEDENOM 15000
    LABELITEM "FULLNAME"
    CLASSITEM "MTFCC"
    FILTER ('[MTFCC]' ne 'C3061')
#    CLASS # 264080
#      EXPRESSION /C3061/
#      STYLE
#        SYMBOL "etc/icons2/poi/-3.png"
#      END
#      LABEL
#        TYPE TRUETYPE
#        FONT "sans"
#        SIZE 8
#        PRIORITY 4
#        POSITION AUTO
#        WRAP " "
#        ALIGN CENTER
#        BUFFER 4
#        COLOR "#291509"
#        OUTLINECOLOR "#ffffff"
#        PARTIALS FALSE
#      END
#    END
    CLASS # 212815
      EXPRESSION /C3081/
      STYLE
        SYMBOL "city_5"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 104401
      EXPRESSION /K2582/
      STYLE
        SYMBOL "etc/icons2/poi/9591.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 67967
      EXPRESSION /C3022|C3023|C3026|C3027|C3062|C3066|C3067|C3070|C3071|C3072|C3073|C3075|C3076|C3078|C3080|C3085|C3088|K2460/
      STYLE
        SYMBOL "circle-filled"
        COLOR "#818181"
        SIZE 5
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 12462
      EXPRESSION /K2451|K2455|K2456/
      STYLE
        SYMBOL "etc/icons2/poi/4581.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 9253
      EXPRESSION /K2540|K2543/
      STYLE
        SYMBOL "etc/icons2/poi/8200.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 2763
      EXPRESSION /K2146|K2165|K2167|K2196/
      STYLE
        SYMBOL "etc/icons2/poi/9590.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 2678
      EXPRESSION /K2181|K2182|K2184|K2185|K2186|K2187|K2188|K2189|K2190/
      STYLE
        SYMBOL "etc/icons2/poi/7522.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 2567
      EXPRESSION /K3544/
      STYLE
        SYMBOL "etc/icons2/poi/9992.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 2303
      EXPRESSION /K1231/
      STYLE
        SYMBOL "etc/icons2/poi/8060.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 1185
      EXPRESSION /K2561/
      STYLE
        SYMBOL "etc/icons2/poi/7992.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 799
      EXPRESSION /K2193|K2194/
      STYLE
        SYMBOL "etc/icons2/poi/9993.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 537
      EXPRESSION /K1236|K1237|K1239/
      STYLE
        SYMBOL "etc/icons2/poi/8231.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 379
      EXPRESSION /K1225|K2454/
      STYLE
        SYMBOL "etc/icons2/poi/4482.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 353
      EXPRESSION /K2195/
      STYLE
        SYMBOL "etc/icons2/poi/9995.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 197
      EXPRESSION /K2191/
      STYLE
        SYMBOL "etc/icons2/poi/9530.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 169
      EXPRESSION /K2452/
      STYLE
        SYMBOL "etc/icons2/poi/4100.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 108
      EXPRESSION /K2110/
      STYLE
        SYMBOL "etc/icons2/poi/8410.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 38
      EXPRESSION /K2453/
      STYLE
        SYMBOL "etc/icons2/poi/4170.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 22
      EXPRESSION /K2400/
      STYLE
        SYMBOL "etc/icons2/poi/9593.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 17
      EXPRESSION /K2545|K2586/
      STYLE
        SYMBOL "etc/icons2/poi/9121.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
    CLASS # 1
      EXPRESSION /C3074/
      STYLE
        SYMBOL "etc/icons2/poi/9715.png"
      END
      LABEL
        TYPE TRUETYPE
        FONT "sans"
        SIZE 8
        PRIORITY 4
        POSITION AUTO
        WRAP " "
        ALIGN CENTER
        BUFFER 4
        COLOR "#291509"
        OUTLINECOLOR "#ffffff"
        PARTIALS FALSE
      END
    END
