insert into as_config (countrycode,countryname,dataset,filter) values ('au','australia','gnaf','PUNCT,SPACE,DASH');

update as_config set grammar = '
# australia.grammar
# Initial grammar for GNAF Australia
# Author: Stephen Woodbridge <woodbri@imaptools.com>

[ADDRESS]
@micro @macro
#@placename @micro @macro

[micro]
@housenumber @streetname
#@unit @housenumber @streetname
#@pobox

[streetname]
@prefixtype @basename @suffixtype
@prefixtype @basename
@basename @suffixtype
@basename

[placename]
PLACEN -> BLDNG -> 0.7
PLACEN WORD -> BLDNG BLDNG -> 0.6
PLACEN WORD WORD -> BLDNG BLDNG BLDNG -> 0.5
PLACEN WORD WORD WORD -> BLDNG BLDNG BLDNG BLDNG -> 0.4
BUILDT -> BLDNG -> 0.7
BUILDT WORD -> BLDNG BLDNG -> 0.6
BUILDT WORD WORD -> BLDNG BLDNG BLDNG -> 0.5
BUILDT WORD WORD WORD -> BLDNG BLDNG BLDNG BLDNG -> 0.4

[unit]
UNITH -> UNITH -> 0.5
UNITH NUMBER -> UNITH UNITT -> 0.4
UNITH WORD -> UNITH UNITT -> 0.4
UNITH WORD WORD -> UNITH UNITT UNITT -> 0.4

[housenumber]
NUMBER -> HOUSE -> 0.3
NUMBER SLASH NUMBER -> IGNORE IGNORE HOUSE -> 0.3
NUMBER DASH NUMBER -> HOUSE IGNORE IGNORE -> 0.3
SINGLE NUMBER -> HOUSE HOUSE -> 0.4
NUMBER SINGLE -> HOUSE HOUSE -> 0.4
SINGLE NUMBER SINGLE -> HOUSE HOUSE HOUSE -> 0.7
DOUBLE NUMBER -> HOUSE HOUSE -> 0.4
NUMBER DOUBLE -> HOUSE HOUSE -> 0.4
DOUBLE NUMBER DOUBLE -> HOUSE HOUSE HOUSE -> 0.7
SINGLE NUMBER DOUBLE -> HOUSE HOUSE HOUSE -> 0.7
DOUBLE NUMBER SINGLE -> HOUSE HOUSE HOUSE -> 0.7
NUMBER NUMBER -> HOUSE HOUSE -> 0.6
WORD NUMBER -> HOUSE HOUSE -> 0.7


[basename]
WORD -> STREET -> 0.6
WORD WORD -> STREET STREET -> 0.5
WORD WORD WORD -> STREET STREET STREET -> 0.45
WORD WORD WORD WORD -> STREET STREET STREET STREET -> 0.4

[prefixtype]
@prefix @ptype
@prefix
@ptype

[suffixtype]
@stype @suffix
@stype
@suffix

[prefix]
QUALIF DIRECT -> QUALIF PREDIR -> 0.8
DIRECT QUALIF -> PREDIR QUALIF -> 0.8
QUALIF -> QUALIF -> 0.8
DIRECT -> PREDIR -> 0.5

[suffix]
DIRECT QUALIF -> SUFDIR QUALIF -> 0.8
QUALIF DIRECT -> QUALIF SUFDIR -> 0.8
DIRECT -> SUFDIR -> 0.5
QUALIF -> QUALIF -> 0.8

[ptype]
TYPE -> PRETYP -> 0.7

[stype]
TYPE -> SUFTYP -> 0.9

[pobox]
NUMBER SINGLE TYPE -> BOXT BOXH BOXH -> 0.2
BOXH NUMBER -> BOXH BOXT -> 0.8

[macro]
@city @prov @postal @nation
@city @prov @nation
@city @prov @postal
@city @prov

[city]
#DIRECT CITY -> CITY CITY -> 0.6
CITY -> CITY -> 0.8
#DIRECT WORD WORD WORD WORD -> CITY CITY CITY CITY CITY -> 0.3
#DIRECT WORD WORD WORD -> CITY CITY CITY CITY -> 0.4
#DIRECT WORD WORD -> CITY CITY CITY -> 0.5
#DIRECT WORD -> CITY CITY -> 0.5
WORD WORD WORD WORD -> CITY CITY CITY CITY -> 0.1
WORD WORD WORD -> CITY CITY CITY -> 0.2
WORD WORD -> CITY CITY -> 0.4
WORD -> CITY -> 0.5

[postal]
QUAD -> POSTAL -> 0.7
NUMBER -> POSTAL -> 0.6

[prov]
PROV -> PROV -> 0.8

[nation]
NATION -> NATION -> 0.8
'
where countrycode='au' and dataset='gnaf';

update as_config set lexicon = $$
LEXICON:	lex-australia.txt	ENG	en_AU
LEXENTRY:	10	10	NUMBER	DETACH
LEXENTRY:	10TH	10TH	WORD,ORD	DETACH
LEXENTRY:	11	11	NUMBER	DETACH
LEXENTRY:	1	1	NUMBER	DETACH
LEXENTRY:	11TH	11TH	WORD,ORD	DETACH
LEXENTRY:	12	12	NUMBER	DETACH
LEXENTRY:	12TH	12TH	WORD,ORD	DETACH
LEXENTRY:	13	13	NUMBER	DETACH
LEXENTRY:	13TH	13TH	WORD,ORD	DETACH
LEXENTRY:	14	14	NUMBER	DETACH
LEXENTRY:	14TH	14TH	WORD,ORD	DETACH
LEXENTRY:	15	15	NUMBER	DETACH
LEXENTRY:	15TH	15TH	WORD,ORD	DETACH
LEXENTRY:	16	16	NUMBER	DETACH
LEXENTRY:	16TH	16TH	WORD,ORD	DETACH
LEXENTRY:	17	17	NUMBER	DETACH
LEXENTRY:	17TH	17TH	WORD,ORD	DETACH
LEXENTRY:	18	18	NUMBER	DETACH
LEXENTRY:	18TH	18TH	WORD,ORD	DETACH
LEXENTRY:	19	19	NUMBER	DETACH
LEXENTRY:	19TH	19TH	WORD,ORD	DETACH
LEXENTRY:	1ST	1ST	WORD,ORD	DETACH
LEXENTRY:	20	20	NUMBER	DETACH
LEXENTRY:	20TH	20TH	WORD,ORD	DETACH
LEXENTRY:	2	2	NUMBER	DETACH
LEXENTRY:	2ND	2ND	WORD,ORD	DETACH
LEXENTRY:	30	30	NUMBER	DETACH
LEXENTRY:	30TH	30TH	WORD,ORD	DETACH
LEXENTRY:	3	3	NUMBER	DETACH
LEXENTRY:	3RD	3RD	WORD,ORD	DETACH
LEXENTRY:	40	40	NUMBER	DETACH
LEXENTRY:	40TH	40TH	WORD,ORD	DETACH
LEXENTRY:	4	4	NUMBER	DETACH
LEXENTRY:	4TH	4TH	WORD,ORD	DETACH
LEXENTRY:	50	50	NUMBER	DETACH
LEXENTRY:	50TH	50TH	WORD,ORD	DETACH
LEXENTRY:	5	5	NUMBER	DETACH
LEXENTRY:	5TH	5TH	WORD,ORD	DETACH
LEXENTRY:	60	60	NUMBER	DETACH
LEXENTRY:	60TH	60TH	WORD,ORD	DETACH
LEXENTRY:	6	6	NUMBER	DETACH
LEXENTRY:	6TH	6TH	WORD,ORD	DETACH
LEXENTRY:	70	70	NUMBER	DETACH
LEXENTRY:	70TH	70TH	WORD,ORD	DETACH
LEXENTRY:	7	7	NUMBER	DETACH
LEXENTRY:	7TH	7TH	WORD,ORD	DETACH
LEXENTRY:	80	80	NUMBER	DETACH
LEXENTRY:	80TH	80TH	WORD,ORD	DETACH
LEXENTRY:	8	8	NUMBER	DETACH
LEXENTRY:	8TH	8TH	WORD,ORD	DETACH
LEXENTRY:	90	90	NUMBER	DETACH
LEXENTRY:	90TH	90TH	WORD,ORD	DETACH
LEXENTRY:	9	9	NUMBER	DETACH
LEXENTRY:	9TH	9TH	WORD,ORD	DETACH
LEXENTRY:	ACADEMY	ACADEMY	PLACEN	DETACH
LEXENTRY:	ACCESS	ACCESS	WORD,TYPE	DETACH
LEXENTRY:	ACCS	ACCESS	WORD,TYPE	DETACH
LEXENTRY:	ACRE	ACRE	WORD,TYPE	DETACH
LEXENTRY:	ACT	ACT	WORD,PROV	DETACH
LEXENTRY:	AGENCY	AGENCY	PLACEN	DETACH
LEXENTRY:	AIRPORT	AIRPORT	PLACEN	DETACH
LEXENTRY:	AIRWALK	AIRWALK	WORD,TYPE	DETACH
LEXENTRY:	ALLEY	ALLEY	WORD,TYPE	DETACH
LEXENTRY:	ALLEY	ALLY	TYPE	DET_SUF
LEXENTRY:	ALLEYWAY	ALLEYWAY	WORD,TYPE	DETACH
LEXENTRY:	ALLY	ALLEY	WORD,TYPE	DETACH
LEXENTRY:	ALLY	ALLY	TYPE	DET_SUF
LEXENTRY:	ALWY	ALLEYWAY	WORD,TYPE	DETACH
LEXENTRY:	AMBL	AMBLE	WORD,TYPE	DETACH
LEXENTRY:	AMBLE	AMBLE	WORD,TYPE	DETACH
LEXENTRY:	APARTMENT	APT	UNITH	DETACH
LEXENTRY:	APP	APPROACH	WORD,TYPE	DETACH
LEXENTRY:	APPROACH	APPROACH	WORD,TYPE	DETACH
LEXENTRY:	APT	APT	UNITH	DETACH
LEXENTRY:	ARCADE	ARCADE	WORD,TYPE	DETACH
LEXENTRY:	ARCADE	ARC	TYPE	DET_SUF
LEXENTRY:	ARC	ARCADE	WORD,TYPE	DETACH
LEXENTRY:	ARC	ARC	TYPE	DET_SUF
LEXENTRY:	ARTERIAL	ARTERIAL	WORD,TYPE	DETACH
LEXENTRY:	ARTERY	ARTERY	WORD,TYPE	DETACH
LEXENTRY:	ARTL	ARTERIAL	WORD,TYPE	DETACH
LEXENTRY:	ARTY	ARTERY	WORD,TYPE	DETACH
LEXENTRY:	AU	AUSTRALIA	NATION	DETACH
LEXENTRY:	AUS	AUSTRALIA	NATION	DETACH
LEXENTRY:	AUSTRALIA	AUSTRALIA	NATION	DETACH
LEXENTRY:	AUSTRALIAN CAPITAL TERRITORY	AUSTRALIAN CAPITAL TERRITORY	WORD,PROV	DETACH
LEXENTRY:	AV	AVENUE	WORD,TYPE	DETAH
LEXENTRY:	AVE	AVE	TYPE	DET_SUF
LEXENTRY:	AVENUE	AVENUE	WORD,TYPE	DETACH
LEXENTRY:	AVENUE	AVE	TYPE	DET_SUF
LEXENTRY:	AWLK	AIRWALK	WORD,TYPE	DETAH
LEXENTRY:	BA	BANAN	WORD,TYPE	DETAH
LEXENTRY:	BAKERY	BAKERY	PLACEN	DETACH
LEXENTRY:	BANAN	BANAN	WORD,TYPE	DETAH
LEXENTRY:	BANK	BANK	PLACEN	DETACH
LEXENTRY:	BANK	BANK	WORD,TYPE	DETAH
LEXENTRY:	BASEMENT	B	UNITH	DETACH
LEXENTRY:	BAY	BAY	WORD,TYPE	DETAH
LEXENTRY:	B	B	SINGLE,WORD,UNITH	DETACH
LEXENTRY:	BCH	BEACH	WORD,TYPE	DETAH
LEXENTRY:	BDGE	BRIDGE	WORD,TYPE	DETAH
LEXENTRY:	BDWY	BROADWAY	WORD,TYPE	DETAH
LEXENTRY:	BEACH	BEACH	WORD,TYPE	DETAH
LEXENTRY:	BEND	BEND	WORD,TYPE	DETAH
LEXENTRY:	BLDG	BLDG	UNITH	DETACH
LEXENTRY:	BOARDWALK	BOARDWALK	WORD,TYPE	DETAH
LEXENTRY:	BOULEVARD	BOULEVARD	WORD,TYPE	DETAH
LEXENTRY:	BOULEVARD	BVD	TYPE	DET_SUF
LEXENTRY:	BOULEVARDE	BOULEVARDE	WORD,TYPE	DETAH
LEXENTRY:	BOWL	BOWL	WORD,TYPE	DETAH
LEXENTRY:	BRACE	BRACE	WORD,TYPE	DETAH
LEXENTRY:	BRAE	BRAE	WORD,TYPE	DETAH
LEXENTRY:	BRAN	BRANCH	WORD,TYPE	DETACH
LEXENTRY:	BRANCH	BRANCH	WORD,TYPE	DETACH
LEXENTRY:	BR	BRACE	WORD,TYPE	DETACH
LEXENTRY:	BRDWLK	BROADWALK	WORD,TYPE	DETACH
LEXENTRY:	BREAK	BREAK	WORD,TYPE	DETACH
LEXENTRY:	BRET	BRETT	WORD,TYPE	DETACH
LEXENTRY:	BRETT	BRETT	WORD,TYPE	DETACH
LEXENTRY:	BRIDGE	BRIDGE	WORD,TYPE	DETACH
LEXENTRY:	BRK	BREAK	WORD,TYPE	DETACH
LEXENTRY:	BROADWALK	BROADWALK	WORD,TYPE	DETACH
LEXENTRY:	BROADWAY	BROADWAY	WORD,TYPE	DETACH
LEXENTRY:	BROW	BROW	WORD,TYPE	DETACH
LEXENTRY:	BSWY	BUSWAY	WORD,TYPE	DETACH
LEXENTRY:	BUILDING	BLDG	UNITH	DETACH
LEXENTRY:	BULL	BULL	WORD,TYPE	DETACH
LEXENTRY:	BUREAU	BUREAU	PLACEN	DETACH
LEXENTRY:	BUSWAY	BUSWAY	WORD,TYPE	DETACH
LEXENTRY:	BVD	BOULEVARD	WORD,TYPE	DETACH
LEXENTRY:	BVD	BVD	TYPE	DET_SUF
LEXENTRY:	BVDE	BOULEVARDE	WORD,TYPE	DETACH
LEXENTRY:	BWLK	BOARDWALK	WORD,TYPE	DETACH
LEXENTRY:	BYPA	BYPASS	WORD,TYPE	DETACH
LEXENTRY:	BYPASS	BYPASS	WORD,TYPE	DETACH
LEXENTRY:	BYWAY	BYWAY	WORD,TYPE	DETACH
LEXENTRY:	BYWY	BYWAY	WORD,TYPE	DETACH
LEXENTRY:	CAFE	CAFE	PLACEN	DETACH
LEXENTRY:	CAFÃ‰	CAFÃ‰	PLACEN	DETACH
LEXENTRY:	CARE OF POST OFFICE	CARE PO	BOXH	DETACH
LEXENTRY:	CARE PO	CARE PO	BOXH	DETACH
LEXENTRY:	CAUSEWAY	CAUSEWAY	WORD,TYPE	DETACH
LEXENTRY:	CCT	CIRCUIT	WORD,TYPE	DETACH
LEXENTRY:	CENTER	CENTER	PLACEN	DETACH
LEXENTRY:	CENTRE	CENTRE	PLACEN	DETACH
LEXENTRY:	CENTRE	CENTRE	WORD,TYPE	DETACH
LEXENTRY:	CENTREWAY	CENTREWAY	WORD,TYPE	DETACH
LEXENTRY:	CHASE	CHASE	WORD,TYPE	DETACH
LEXENTRY:	CH	CHASE	WORD,TYPE	DETACH
LEXENTRY:	CINEMA	CINEMA	PLACEN	DETACH
LEXENTRY:	CIR	CIRCLE	WORD,TYPE	DETACH
LEXENTRY:	CIRCLE	CIRCLE	WORD,TYPE	DETACH
LEXENTRY:	CIRCLET	CIRCLET	WORD,TYPE	DETACH
LEXENTRY:	CIRCUIT	CIRCUIT	WORD,TYPE	DETACH
LEXENTRY:	CIRCUS	CIRCUS	WORD,TYPE	DETACH
LEXENTRY:	CL	CLOSE	WORD,TYPE	DETACH
LEXENTRY:	CL	CL	TYPE	DET_SUF
LEXENTRY:	CLDE	COLONNADE	WORD,TYPE	DETACH
LEXENTRY:	CLOSE	CLOSE	WORD,TYPE	DETACH
LEXENTRY:	CLOSE	CL	TYPE	DET_SUF
LEXENTRY:	CLR	CLUSTER	WORD,TYPE	DETACH
LEXENTRY:	CLT	CIRCLET	WORD,TYPE	DETACH
LEXENTRY:	CLUSTER	CLUSTER	WORD,TYPE	DETACH
LEXENTRY:	CMA	CMA	BOXH	DETACH
LEXENTRY:	CMB	CMB	BOXH	DETACH
LEXENTRY:	CMMN	COMMON	WORD,TYPE	DETACH
LEXENTRY:	CMMNS	COMMONS	WORD,TYPE	DETACH
LEXENTRY:	CNCD	CONCORD	WORD,TYPE	DETACH
LEXENTRY:	CNR	CORNER	WORD,TYPE	DETACH
LEXENTRY:	CNTN	CONNECTION	WORD,TYPE	DETACH
LEXENTRY:	CNWY	CENTREWAY	WORD,TYPE	DETACH
LEXENTRY:	CO	CO	PLACEN	DETACH
LEXENTRY:	COLLEGE	COLLEGE	PLACEN	DETACH
LEXENTRY:	COLONNADE	COLONNADE	WORD,TYPE	DETACH
LEXENTRY:	COMMON	COMMON	WORD,TYPE	DETACH
LEXENTRY:	COMMONS	COMMONS	WORD,TYPE	DETACH
LEXENTRY:	COMMUNITY MAIL BAG	CMB	BOXH	DETACH
LEXENTRY:	COMMUNITY POSTAL AGENT	CPA	BOXH	DETACH
LEXENTRY:	COMPANY	COMPANY	PLACEN	DETACH
LEXENTRY:	COMUNITY MAIL AGENT	CMA	BOXH	DETACH
LEXENTRY:	CON	CONCOURSE	WORD,TYPE	DETACH
LEXENTRY:	CONCORD	CONCORD	WORD,TYPE	DETACH
LEXENTRY:	CONCOURSE	CONCOURSE	WORD,TYPE	DETACH
LEXENTRY:	CONNECTION	CONNECTION	WORD,TYPE	DETACH
LEXENTRY:	CONSERVATORY	CONSERVATORY	PLACEN	DETACH
LEXENTRY:	COPSE	COPSE	WORD,TYPE	DETACH
LEXENTRY:	CORN	CORNER	WORD,TYPE	DETACH
LEXENTRY:	CORNER	CORNER	WORD,TYPE	DETACH
LEXENTRY:	CORP	CORP	PLACEN	DETACH
LEXENTRY:	CORPORATION	CORPORATION	PLACEN	DETACH
LEXENTRY:	CORSO	CORSO	WORD,TYPE	DETACH
LEXENTRY:	COURSE	COURSE	WORD,TYPE	DETACH
LEXENTRY:	COURT	COURT	WORD,TYPE	DETACH
LEXENTRY:	COURT	CT	TYPE	DET_SUF
LEXENTRY:	COURTYARD	COURTYARD	WORD,TYPE	DETACH
LEXENTRY:	COVE	COVE	WORD,TYPE	DETACH
LEXENTRY:	CPA	CPA	BOXH	DETACH
LEXENTRY:	CPS	COPSE	WORD,TYPE	DETACH
LEXENTRY:	CR	CRESCENT	WORD,TYPE	DETACH
LEXENTRY:	CRCS	CIRCUS	WORD,TYPE	DETACH
LEXENTRY:	CRESCENT	CRESCENT	WORD,TYPE	DETACH
LEXENTRY:	CRESCENT	CRES	TYPE	DET_SUF
LEXENTRY:	CRES	CRES	TYPE	DET_SUF
LEXENTRY:	CREST	CREST	WORD,TYPE	DETACH
LEXENTRY:	CRF	CRIEF	WORD,TYPE	DETACH
LEXENTRY:	CRIEF	CRIEF	WORD,TYPE	DETACH
LEXENTRY:	CRK	CROOK	WORD,TYPE	DETACH
LEXENTRY:	CROOK	CROOK	WORD,TYPE	DETACH
LEXENTRY:	CROSS	CROSS	WORD,TYPE	DETACH
LEXENTRY:	CROSSING	CROSSING	WORD,TYPE	DETACH
LEXENTRY:	CRSE	COURSE	WORD,TYPE	DETACH
LEXENTRY:	CRSG	CROSSING	WORD,TYPE	DETACH
LEXENTRY:	CRSS	CROSS	WORD,TYPE	DETACH
LEXENTRY:	CRST	CREST	WORD,TYPE	DETACH
LEXENTRY:	CRUISEWAY	CRUISEWAY	WORD,TYPE	DETACH
LEXENTRY:	CSAC	CUL-DE-SAC	WORD,TYPE	DETACH
LEXENTRY:	CSO	CORSO	WORD,TYPE	DETACH
LEXENTRY:	CSWY	CAUSEWAY	WORD,TYPE	DETACH
LEXENTRY:	CT	COURT	WORD,TYPE	DETACH
LEXENTRY:	CT	CT	TYPE	DET_SUF
LEXENTRY:	CTR	CENTRE	WORD,TYPE	DETACH
LEXENTRY:	CTYD	COURTYARD	WORD,TYPE	DETACH
LEXENTRY:	CUL-DE-SAC	CUL-DE-SAC	WORD,TYPE	DETACH
LEXENTRY:	CUT	CUT	WORD,TYPE	DETACH
LEXENTRY:	CUTT	CUTTING	WORD,TYPE	DETACH
LEXENTRY:	CUTTING	CUTTING	WORD,TYPE	DETACH
LEXENTRY:	CUWY	CRUISEWAY	WORD,TYPE	DETACH
LEXENTRY:	DALE	DALE	WORD,TYPE	DETACH
LEXENTRY:	DASH	DASH	WORD,TYPE	DETACH
LEXENTRY:	DE	DEVIATION	WORD,TYPE	DETACH
LEXENTRY:	DELL	DELL	WORD,TYPE	DETACH
LEXENTRY:	DENE	DENE	WORD,TYPE	DETACH
LEXENTRY:	DEVIATION	DEVIATION	WORD,TYPE	DETACH
LEXENTRY:	DIP	DIP	WORD,TYPE	DETACH
LEXENTRY:	DISTRIBUTOR	DISTRIBUTOR	WORD,TYPE	DETACH
LEXENTRY:	DIV	DIVIDE	WORD,TYPE	DETACH
LEXENTRY:	DIVIDE	DIVIDE	WORD,TYPE	DETACH
LEXENTRY:	DOCK	DOCK	WORD,TYPE	DETACH
LEXENTRY:	DOMAIN	DOMAIN	WORD,TYPE	DETACH
LEXENTRY:	DOM	DOMAIN	WORD,TYPE	DETACH
LEXENTRY:	DOWN	DOWN	WORD,TYPE	DETACH
LEXENTRY:	DOWNS	DOWNS	WORD,TYPE	DETACH
LEXENTRY:	DR	DRIVE	WORD,TYPE	DETACH
LEXENTRY:	DR	DR	TYPE	DET_SUF
LEXENTRY:	DRIVE	DRIVE	WORD,TYPE	DETACH
LEXENTRY:	DRIVE	DR	TYPE	DET_SUF
LEXENTRY:	DRIVEWAY	DRIVEWAY	WORD,TYPE	DETACH
LEXENTRY:	DSTR	DISTRIBUTOR	WORD,TYPE	DETACH
LEXENTRY:	DVWY	DRIVEWAY	WORD,TYPE	DETACH
LEXENTRY:	DWNS	DOWNS	WORD,TYPE	DETACH
LEXENTRY:	EASEMENT	EASEMENT	WORD,TYPE	DETACH
LEXENTRY:	EAST	EAST	WORD,TYPE	DETACH
LEXENTRY:	EAST	E	DIRECT	DETACH
LEXENTRY:	EDGE	EDGE	WORD,TYPE	DETACH
LEXENTRY:	E	E	SINGLE,WORD,DIRECT	DETACH
LEXENTRY:	EIGHT	8	NUMBER	DETACH
LEXENTRY:	EIGHTEEN	18	NUMBER	DETACH
LEXENTRY:	EIGHTEENTH	18TH	WORD,ORD	DETACH
LEXENTRY:	EIGHTH	8TH	WORD,ORD	DETACH
LEXENTRY:	EIGHTIETH	80TH	WORD,ORD	DETACH
LEXENTRY:	EIGHTY	80	NUMBER	DETACH
LEXENTRY:	ELB	ELBOW	WORD,TYPE	DETACH
LEXENTRY:	ELBOW	ELBOW	WORD,TYPE	DETACH
LEXENTRY:	ELEVEN	11	NUMBER	DETACH
LEXENTRY:	ELEVENTH	11TH	WORD,ORD	DETACH
LEXENTRY:	END	END	WORD,TYPE	DETACH
LEXENTRY:	ENT	ENTRANCE	WORD,TYPE	DETACH
LEXENTRY:	ENTRANCE	ENTRANCE	WORD,TYPE	DETACH
LEXENTRY:	ESMT	EASEMENT	WORD,TYPE	DETACH
LEXENTRY:	ESP	ESPLANADE	WORD,TYPE	DETACH
LEXENTRY:	ESP	ESP	TYPE	DET_SUF
LEXENTRY:	ESPLANADE	ESPLANADE	WORD,TYPE	DETACH
LEXENTRY:	ESPLANADE	ESP	TYPE	DET_SUF
LEXENTRY:	ESTATE	ESTATE	WORD,TYPE	DETACH
LEXENTRY:	EST	ESTATE	WORD,TYPE	DETACH
LEXENTRY:	EXP	EXPRESSWAY	WORD,TYPE	DETACH
LEXENTRY:	EXPRESSWAY	EXPRESSWAY	WORD,TYPE	DETACH
LEXENTRY:	EXTENSION	EXTENSION	WORD,TYPE	DETACH
LEXENTRY:	EXTN	EXTENSION	WORD,TYPE	DETACH
LEXENTRY:	FACTORY	FY	UNITH	DETACH
LEXENTRY:	FAIRWAY	FAIRWAY	WORD,TYPE	DETACH
LEXENTRY:	FAWY	FAIRWAY	WORD,TYPE	DETACH
LEXENTRY:	FBRK	FIREBREAK	WORD,TYPE	DETACH
LEXENTRY:	F	F	SINGLE,WORD,UNITH	DETACH
LEXENTRY:	FIFTEEN	15	NUMBER	DETACH
LEXENTRY:	FIFTEENTH	15TH	WORD,ORD	DETACH
LEXENTRY:	FIFTH	5TH	WORD,ORD	DETACH
LEXENTRY:	FIFTIETH	50TH	WORD,ORD	DETACH
LEXENTRY:	FIFTY	50	NUMBER	DETACH
LEXENTRY:	FIREBREAK	FIREBREAK	WORD,TYPE	DETACH
LEXENTRY:	FIRELINE	FIRELINE	WORD,TYPE	DETACH
LEXENTRY:	FIRETRACK	FIRETRACK	WORD,TYPE	DETACH
LEXENTRY:	FIRETRAIL	FIRETRAIL	WORD,TYPE	DETACH
LEXENTRY:	FIRST	1ST	WORD,ORD	DETACH
LEXENTRY:	FITR	FIRETRAIL	WORD,TYPE	DETACH
LEXENTRY:	FIVE	5	NUMBER	DETACH
LEXENTRY:	FLAT	FLAT	WORD,TYPE	DETACH
LEXENTRY:	FLAT	F	UNITH	DETACH
LEXENTRY:	FLATS	FLATS	WORD,TYPE	DETACH
LEXENTRY:	FL	FL	UNITH	DETACH
LEXENTRY:	FLNE	FIRELINE	WORD,TYPE	DETACH
LEXENTRY:	FLOOR	FL	UNITH	DETACH
LEXENTRY:	FLTS	FLATS	WORD,TYPE	DETACH
LEXENTRY:	FOLLOW	FOLLOW	WORD,TYPE	DETACH
LEXENTRY:	FOLW	FOLLOW	WORD,TYPE	DETACH
LEXENTRY:	FOOTWAY	FOOTWAY	WORD,TYPE	DETACH
LEXENTRY:	FORD	FORD	WORD,TYPE	DETACH
LEXENTRY:	FORESHORE	FORESHORE	WORD,TYPE	DETACH
LEXENTRY:	FORK	FORK	WORD,TYPE	DETACH
LEXENTRY:	FORMATION	FORMATION	WORD,TYPE	DETACH
LEXENTRY:	FORM	FORMATION	WORD,TYPE	DETACH
LEXENTRY:	FORTIETH	40TH	WORD,ORD	DETACH
LEXENTRY:	FORTY	40	NUMBER	DETACH
LEXENTRY:	FOUR	4	NUMBER	DETACH
LEXENTRY:	FOURTEEN	14	NUMBER	DETACH
LEXENTRY:	FOURTEENTH	14TH	WORD,ORD	DETACH
LEXENTRY:	FOUTH	4TH	WORD,ORD	DETACH
LEXENTRY:	FREEWAY	FREEWAY	WORD,TYPE	DETACH
LEXENTRY:	FRNT	FRONT	WORD,TYPE	DETACH
LEXENTRY:	FRONTAGE	FRONTAGE	WORD,TYPE	DETACH
LEXENTRY:	FRONT	FRONT	WORD,TYPE	DETACH
LEXENTRY:	FRTG	FRONTAGE	WORD,TYPE	DETACH
LEXENTRY:	FSHR	FORESHORE	WORD,TYPE	DETACH
LEXENTRY:	FTRK	FIRETRACK	WORD,TYPE	DETACH
LEXENTRY:	FTWY	FOOTWAY	WORD,TYPE	DETACH
LEXENTRY:	FUND	FUND	PLACEN	DETACH
LEXENTRY:	FWY	FREEWAY	WORD,TYPE	DETACH
LEXENTRY:	FY	FY	UNITH	DETACH
LEXENTRY:	GALLERY	GALLERY	PLACEN	DETACH
LEXENTRY:	GAP	GAP	WORD,TYPE	DETACH
LEXENTRY:	GARDEN	GARDEN	PLACEN	DETACH
LEXENTRY:	GARDEN	GARDEN	WORD,TYPE	DETACH
LEXENTRY:	GARDENS	GARDENS	WORD,TYPE	DETACH
LEXENTRY:	GATE	GATE	WORD,TYPE	DETACH
LEXENTRY:	GATEWAY	GATEWAY	WORD,TYPE	DETACH
LEXENTRY:	GDN	GARDEN	WORD,TYPE	DETACH
LEXENTRY:	GDNS	GARDENS	WORD,TYPE	DETACH
LEXENTRY:	GENERAL POST OFFICE BOX 	GPO BOX	BOXH	DETACH
LEXENTRY:	G	G	SINGLE,WORD,UNITH	DETACH
LEXENTRY:	GLADE	GLADE	WORD,TYPE	DETACH
LEXENTRY:	GLDE	GLADE	WORD,TYPE	DETACH
LEXENTRY:	GLEN	GLEN	WORD,TYPE	DETACH
LEXENTRY:	GLY	GULLY	WORD,TYPE	DETACH
LEXENTRY:	GPO BOX	GPO BOX	BOXH	DETACH
LEXENTRY:	GRA	GRANGE	WORD,TYPE	DETACH
LEXENTRY:	GRANGE	GRANGE	WORD,TYPE	DETACH
LEXENTRY:	GREEN	GREEN	WORD,TYPE	DETACH
LEXENTRY:	GR	GROVE	WORD,TYPE	DETACH
LEXENTRY:	GR	GR	TYPE	DET_SUF
LEXENTRY:	GRN	GREEN	WORD,TYPE	DETACH
LEXENTRY:	GROUND FLOOR	GROUND FLOOR	UNITH	DETACH
LEXENTRY:	GROUP	GROUP	PLACEN	DETACH
LEXENTRY:	GROVE	GROVE	WORD,TYPE	DETACH
LEXENTRY:	GROVE	GR	TYPE	DET_SUF
LEXENTRY:	GTE	GATE	WORD,TYPE	DETACH
LEXENTRY:	GULLY	GULLY	WORD,TYPE	DETACH
LEXENTRY:	GWY	GATEWAY	WORD,TYPE	DETACH
LEXENTRY:	GYMNASIUM	GYMNASIUM	PLACEN	DETACH
LEXENTRY:	HALL	HALL	PLACEN	DETACH
LEXENTRY:	HARBOUR	HARBOUR	WORD,TYPE	DETACH
LEXENTRY:	HAVEN	HAVEN	WORD,TYPE	DETACH
LEXENTRY:	HEATH	HEATH	WORD,TYPE	DETACH
LEXENTRY:	HEIGHTS	HEIGHTS	WORD,TYPE	DETACH
LEXENTRY:	HIGHROAD	HIGHROAD	WORD,TYPE	DETACH
LEXENTRY:	HIGHWAY	HIGHWAY	WORD,TYPE	DETACH
LEXENTRY:	HIGHWAY	HWY	TYPE	DET_SUF
LEXENTRY:	HIKE	HIKE	WORD,TYPE	DETACH
LEXENTRY:	HILL	HILL	WORD,TYPE	DETACH
LEXENTRY:	HILLS	HILLS	WORD,TYPE	DETACH
LEXENTRY:	HIRD	HIGHROAD	WORD,TYPE	DETACH
LEXENTRY:	HLLW	HOLLOW	WORD,TYPE	DETACH
LEXENTRY:	HOLLOW	HOLLOW	WORD,TYPE	DETACH
LEXENTRY:	HOSPITAL	HOSPITAL	PLACEN	DETACH
LEXENTRY:	HOTEL	HOTEL	PLACEN	DETACH
LEXENTRY:	HOUSE	HOUSE	PLACEN	DETACH
LEXENTRY:	HRBR	HARBOUR	WORD,TYPE	DETACH
LEXENTRY:	HTH	HEATH	WORD,TYPE	DETACH
LEXENTRY:	HTS	HEIGHTS	WORD,TYPE	DETACH
LEXENTRY:	HUB	HUB	WORD,TYPE	DETACH
LEXENTRY:	HVN	HAVEN	WORD,TYPE	DETACH
LEXENTRY:	HWY	HIGHWAY	WORD,TYPE	DETACH
LEXENTRY:	HWY	HWY	TYPE	DET_SUF
LEXENTRY:	ID	ISLAND	WORD,TYPE	DETACH
LEXENTRY:	INC	INC	PLACEN	DETACH
LEXENTRY:	INCORPORATED	INCORPORATED	PLACEN	DETACH
LEXENTRY:	INLET	INLET	WORD,TYPE	DETACH
LEXENTRY:	INLT	INLET	WORD,TYPE	DETACH
LEXENTRY:	INSTITUTE	INSTITUTE	PLACEN	DETACH
LEXENTRY:	INTERCHANGE	INTERCHANGE	WORD,TYPE	DETACH
LEXENTRY:	INTG	INTERCHANGE	WORD,TYPE	DETACH
LEXENTRY:	ISLAND	ISLAND	WORD,TYPE	DETACH
LEXENTRY:	JNC	JUNCTION	WORD,TYPE	DETACH
LEXENTRY:	JUNCTION	JUNCTION	WORD,TYPE	DETACH
LEXENTRY:	KEY	KEY	WORD,TYPE	DETACH
LEXENTRY:	KEYS	KEYS	WORD,TYPE	DETACH
LEXENTRY:	KNOL	KNOLL	WORD,TYPE	DETACH
LEXENTRY:	KNOLL	KNOLL	WORD,TYPE	DETACH
LEXENTRY:	LAB	LAB	PLACEN	DETACH
LEXENTRY:	LABORATORIES	LABORATORIES	PLACEN	DETACH
LEXENTRY:	LABORATORY	LABORATORY	PLACEN	DETACH
LEXENTRY:	LABS	LABS	PLACEN	DETACH
LEXENTRY:	LADDER	LADDER	WORD,TYPE	DETACH
LEXENTRY:	LADR	LADDER	WORD,TYPE	DETACH
LEXENTRY:	LANDING	LANDING	WORD,TYPE	DETACH
LEXENTRY:	LANE	LANE	TYPE	DET_SUF
LEXENTRY:	LANE	LANE	WORD,TYPE	DETACH
LEXENTRY:	LANEWAY	LANEWAY	WORD,TYPE	DETACH
LEXENTRY:	LDG	LANDING	WORD,TYPE	DETACH
LEXENTRY:	LEADER	LEADER	WORD,TYPE	DETACH
LEXENTRY:	LEAD	LEAD	WORD,TYPE	DETACH
LEXENTRY:	LEDR	LEADER	WORD,TYPE	DETACH
LEXENTRY:	LEVEL	L	UNITH	DETACH
LEXENTRY:	LG	LOWER GROUND FLOOR	UNITH	DETACH
LEXENTRY:	LIABILITY	LIABILITY	PLACEN	DETACH
LEXENTRY:	LIBRARY	LIBRARY	PLACEN	DETACH
LEXENTRY:	LIMITED	LIMITED	PLACEN	DETACH
LEXENTRY:	LINE	LINE	WORD,TYPE	DETACH
LEXENTRY:	LINK	LINK	WORD,TYPE	DETACH
LEXENTRY:	LKT	LOOKOUT	WORD,TYPE	DETACH
LEXENTRY:	L	L	SINGLE,WORD,UNITH	DETACH
LEXENTRY:	LNWY	LANEWAY	WORD,TYPE	DETACH
LEXENTRY:	LOCKED BAG	LOCKED BAG	BOXH	DETACH
LEXENTRY:	LOOKOUT	LOOKOUT	WORD,TYPE	DETACH
LEXENTRY:	LOOP	LOOP	WORD,TYPE	DETACH
LEXENTRY:	LOWER GROUND FLOOR	LOWER GROUND FLOOR	UNITH	DETACH
LEXENTRY:	LTD	LTD	PLACEN	DETACH
LEXENTRY:	LYNNE	LYNNE	WORD,TYPE	DETACH
LEXENTRY:	LYNN	LYNNE	WORD,TYPE	DETACH
LEXENTRY:	MAIL SERVICE	MS	BOXH	DETACH
LEXENTRY:	MALL	MALL	PLACEN	DETACH
LEXENTRY:	MALL	MALL	WORD,TYPE	DETACH
LEXENTRY:	MANOR	MANOR	WORD,TYPE	DETACH
LEXENTRY:	MANR	MANOR	WORD,TYPE	DETACH
LEXENTRY:	MARINE BERTH	MB	UNITH	DETACH
LEXENTRY:	MARKET	MARKET	PLACEN	DETACH
LEXENTRY:	MART	MART	WORD,TYPE	DETACH
LEXENTRY:	MAZE	MAZE	WORD,TYPE	DETACH
LEXENTRY:	MB	MB	UNITH	DETACH
LEXENTRY:	MEAD	MEAD	WORD,TYPE	DETACH
LEXENTRY:	MEANDER	MEANDER	WORD,TYPE	DETACH
LEXENTRY:	MEW	MEW	WORD,TYPE	DETACH
LEXENTRY:	MEWS	MEWS	WORD,TYPE	DETACH
LEXENTRY:	MEZZANINE	M	UNITH	DETACH
LEXENTRY:	MILE	MILE	WORD,TYPE	DETACH
LEXENTRY:	M	M	SINGLE,WORD,UNITH	DETACH
LEXENTRY:	MNDR	MEANDER	WORD,TYPE	DETACH
LEXENTRY:	MOTORWAY	MOTORWAY	WORD,TYPE	DETACH
LEXENTRY:	MS	MS	BOXH	DETACH
LEXENTRY:	MTWY	MOTORWAY	WORD,TYPE	DETACH
LEXENTRY:	MUSEUM	MUSEUM	PLACEN	DETACH
LEXENTRY:	MZ	MAZE	WORD,TYPE	DETACH
LEXENTRY:	NE	NE	DIRECT	DETACH
LEXENTRY:	NEW SOUTH WALES	NEW SOUTH WALES	WORD,PROV	DETACH
LEXENTRY:	NINE	9	NUMBER	DETACH
LEXENTRY:	NINETEEN	19	NUMBER	DETACH
LEXENTRY:	NINETEENTH	19TH	WORD,ORD	DETACH
LEXENTRY:	NINETIETH	90TH	WORD,ORD	DETACH
LEXENTRY:	NINETY	90	NUMBER	DETACH
LEXENTRY:	NINTH	9TH	WORD,ORD	DETACH
LEXENTRY:	NL	NL	PLACEN	DETACH
LEXENTRY:	N	N	SINGLE,WORD,DIRECT	DETACH
LEXENTRY:	NOOK	NOOK	WORD,TYPE	DETACH
LEXENTRY:	NORTHEAST	NE	DIRECT	DETACH
LEXENTRY:	NORTHERN TERRITORY	NORTHERN TERRITORY	WORD,PROV	DETACH
LEXENTRY:	NORTH	N	DIRECT	DETACH
LEXENTRY:	NORTH	NORTH	WORD,TYPE	DETACH
LEXENTRY:	NORTHWEST	NW	DIRECT	DETACH
LEXENTRY:	NSW	NSW	WORD,PROV	DETACH
LEXENTRY:	NTH	NORTH	WORD,TYPE	DETACH
LEXENTRY:	NT	NT	WORD,PROV	DETACH
LEXENTRY:	NULL	NULL	WORD,TYPE	DETACH
LEXENTRY:	NW	NW	DIRECT	DETACH
LEXENTRY:	OFFICE	OFF	UNITH	DETACH
LEXENTRY:	OFF	OFF	UNITH	DETACH
LEXENTRY:	ONE	1	NUMBER	DETACH
LEXENTRY:	OTHER TERRITORIES	OTHER TERRITORIES	WORD,PROV	DETACH
LEXENTRY:	OTLK	OUTLOOK	WORD,TYPE	DETACH
LEXENTRY:	OTLT	OUTLET	WORD,TYPE	DETACH
LEXENTRY:	OT	OT	WORD,PROV	DETACH
LEXENTRY:	OUTLET	OUTLET	WORD,TYPE	DETACH
LEXENTRY:	OUTLOOK	OUTLOOK	WORD,TYPE	DETACH
LEXENTRY:	OVAL	OVAL	WORD,TYPE	DETACH
LEXENTRY:	PALMS	PALMS	WORD,TYPE	DETACH
LEXENTRY:	PARADE	PARADE	WORD,TYPE	DETACH
LEXENTRY:	PARADE	PDE	TYPE	DET_SUF
LEXENTRY:	PARADISE	PARADISE	WORD,TYPE	DETACH
LEXENTRY:	PARK	PARK	PLACEN	DETACH
LEXENTRY:	PARK	PARK	WORD,TYPE	DETACH
LEXENTRY:	PARKWAY	PARKWAY	WORD,TYPE	DETACH
LEXENTRY:	PART	PART	WORD,TYPE	DETACH
LEXENTRY:	PASSAGE	PASSAGE	WORD,TYPE	DETACH
LEXENTRY:	PASS	PASS	WORD,TYPE	DETACH
LEXENTRY:	PATH	PATH	WORD,TYPE	DETACH
LEXENTRY:	PATHWAY	PATHWAY	WORD,TYPE	DETACH
LEXENTRY:	PDE	PARADE	WORD,TYPE	DETACH
LEXENTRY:	PDE	PDE	TYPE	DET_SUF
LEXENTRY:	PENINSULA	PENINSULA	WORD,TYPE	DETACH
LEXENTRY:	PIAZ	PIAZZA	WORD,TYPE	DETACH
LEXENTRY:	PIAZZA	PIAZZA	WORD,TYPE	DETACH
LEXENTRY:	PKT	POCKET	WORD,TYPE	DETACH
LEXENTRY:	PLACE	PLACE	WORD,TYPE	DETACH
LEXENTRY:	PLACE	PL	TYPE	DET_SUF
LEXENTRY:	PLAZA	PLAZA	WORD,TYPE	DETACH
LEXENTRY:	PLC	PLC	PLACEN	DETACH
LEXENTRY:	PLMS	PALMS	WORD,TYPE	DETACH
LEXENTRY:	PL	PLACE	WORD,TYPE	DETACH
LEXENTRY:	P/L	P/L	PLACEN	DETACH
LEXENTRY:	PL	PL	PLACEN,TYPE	DETACH,DET_SUF
LEXENTRY:	PLZA	PLAZA	WORD,TYPE	DETACH
LEXENTRY:	PNT	POINT	WORD,TYPE	DETACH
LEXENTRY:	PO BOX	PO BOX	BOXH	DETACH
LEXENTRY:	POCKET	POCKET	WORD,TYPE	DETACH
LEXENTRY:	POINT	POINT	WORD,TYPE	DETACH
LEXENTRY:	PORT	PORT	WORD,TYPE	DETACH
LEXENTRY:	POST OFFICE BOX	PO BOX	BOXH	DETACH
LEXENTRY:	PRDS	PARADISE	WORD,TYPE	DETACH
LEXENTRY:	PRECINCT	PRECINCT	WORD,TYPE	DETACH
LEXENTRY:	PREC	PRECINCT	WORD,TYPE	DETACH
LEXENTRY:	PRIVATE BAG	PRIVATE BAG	BOXH	DETACH
LEXENTRY:	PROMENADE	PROMENADE	WORD,TYPE	DETACH
LEXENTRY:	PROM	PROMENADE	WORD,TYPE	DETACH
LEXENTRY:	PROPRIETARY	PROPRIETARY	PLACEN	DETACH
LEXENTRY:	PRST	PURSUIT	WORD,TYPE	DETACH
LEXENTRY:	PSGE	PASSAGE	WORD,TYPE	DETACH
LEXENTRY:	PSLA	PENINSULA	WORD,TYPE	DETACH
LEXENTRY:	PTY	PTY	PLACEN	DETACH
LEXENTRY:	PURSUIT	PURSUIT	WORD,TYPE	DETACH
LEXENTRY:	PWAY	PATHWAY	WORD,TYPE	DETACH
LEXENTRY:	PWY	PARKWAY	WORD,TYPE	DETACH
LEXENTRY:	QDRT	QUADRANT	WORD,TYPE	DETACH
LEXENTRY:	QLD	QLD	WORD,PROV	DETACH
LEXENTRY:	QUAD	QUAD	WORD,TYPE	DETACH
LEXENTRY:	QUADRANT	QUADRANT	WORD,TYPE	DETACH
LEXENTRY:	QUAY	QUAY	WORD,TYPE	DETACH
LEXENTRY:	QUAYS	QUAYS	WORD,TYPE	DETACH
LEXENTRY:	QUEENSLAND	QUEENSLAND	WORD,PROV	DETACH
LEXENTRY:	QY	QUAY	WORD,TYPE	DETACH
LEXENTRY:	QYS	QUAYS	WORD,TYPE	DETACH
LEXENTRY:	RAMBLE	RAMBLE	WORD,TYPE	DETACH
LEXENTRY:	RAMP	RAMP	WORD,TYPE	DETACH
LEXENTRY:	RANGE	RANGE	WORD,TYPE	DETACH
LEXENTRY:	RCH	REACH	WORD,TYPE	DETACH
LEXENTRY:	RDGE	RIDGE	WORD,TYPE	DETACH
LEXENTRY:	RD	RD	TYPE	DET_SUF
LEXENTRY:	RD	ROAD	WORD,TYPE	DETACH
LEXENTRY:	RDS	ROADS	WORD,TYPE	DETACH
LEXENTRY:	RDWY	ROADWAY	WORD,TYPE	DETACH
LEXENTRY:	REACH	REACH	WORD,TYPE	DETACH
LEXENTRY:	REEF	REEF	WORD,TYPE	DETACH
LEXENTRY:	RESERVE	RESERVE	WORD,TYPE	DETACH
LEXENTRY:	RES	RESERVE	WORD,TYPE	DETACH
LEXENTRY:	RESTAURANT	RESTAURANT	PLACEN	DETACH
LEXENTRY:	REST	REST	WORD,TYPE	DETACH
LEXENTRY:	RETREAT	RETREAT	WORD,TYPE	DETACH
LEXENTRY:	RETURN	RETURN	WORD,TYPE	DETACH
LEXENTRY:	RIDE	RIDE	WORD,TYPE	DETACH
LEXENTRY:	RIDGE	RIDGE	WORD,TYPE	DETACH
LEXENTRY:	RIGHT OF WAY	RIGHT OF WAY	WORD,TYPE	DETACH
LEXENTRY:	RING	RING	WORD,TYPE	DETACH
LEXENTRY:	RISE	RISE	WORD,TYPE	DETACH
LEXENTRY:	RISING	RISING	WORD,TYPE	DETACH
LEXENTRY:	RIVER	RIVER	WORD,TYPE	DETACH
LEXENTRY:	RMBL	RAMBLE	WORD,TYPE	DETACH
LEXENTRY:	RMB	RMB	BOXH	DETACH
LEXENTRY:	RM	RM	UNITH	DETACH
LEXENTRY:	RMS	RMS	BOXH	DETACH
LEXENTRY:	RND	ROUND	WORD,TYPE	DETACH
LEXENTRY:	RNGE	RANGE	WORD,TYPE	DETACH
LEXENTRY:	ROAD	RD	TYPE	DET_SUF
LEXENTRY:	ROAD	ROAD	WORD,TYPE	DETACH
LEXENTRY:	ROADSIDE DELIVERY	RSD	BOXH	DETACH
LEXENTRY:	ROADSIDE MAIL BAG	RMB	BOXH	DETACH
LEXENTRY:	ROADSIDE MAIL BOX	RMB	BOXH	DETACH
LEXENTRY:	ROADSIDE MAIL SERVICE	RMS	BOXH	DETACH
LEXENTRY:	ROADS	ROADS	WORD,TYPE	DETACH
LEXENTRY:	ROADWAY	ROADWAY	WORD,TYPE	DETACH
LEXENTRY:	ROFW	RIGHT OF WAY	WORD,TYPE	DETACH
LEXENTRY:	ROOM	RM	UNITH	DETACH
LEXENTRY:	ROTARY	ROTARY	WORD,TYPE	DETACH
LEXENTRY:	ROUND	ROUND	WORD,TYPE	DETACH
LEXENTRY:	ROUTE	ROUTE	WORD,TYPE	DETACH
LEXENTRY:	ROWE	ROWE	WORD,TYPE	DETACH
LEXENTRY:	ROW	ROW	WORD,TYPE	DETACH
LEXENTRY:	RSD	RSD	BOXH	DETACH
LEXENTRY:	RSNG	RISING	WORD,TYPE	DETACH
LEXENTRY:	RTE	ROUTE	WORD,TYPE	DETACH
LEXENTRY:	RTN	RETURN	WORD,TYPE	DETACH
LEXENTRY:	RTT	RETREAT	WORD,TYPE	DETACH
LEXENTRY:	RTY	ROTARY	WORD,TYPE	DETACH
LEXENTRY:	RUE	RUE	WORD,TYPE	DETACH
LEXENTRY:	RUN	RUN	WORD,TYPE	DETACH
LEXENTRY:	RVR	RIVER	WORD,TYPE	DETACH
LEXENTRY:	SAINT	ST	WORD	DETACH
LEXENTRY:	SA	SA	WORD,PROV	DETACH
LEXENTRY:	SBWY	SUBWAY	WORD,TYPE	DETACH
LEXENTRY:	SCHOOL	SCHOOL	PLACEN	DETACH
LEXENTRY:	SECOND	2ND	WORD,ORD	DETACH
LEXENTRY:	SERVICEWAY	SERVICEWAY	WORD,TYPE	DETACH
LEXENTRY:	SE	SE	DIRECT,UNITH	DETACH
LEXENTRY:	SEVEN	7	NUMBER	DETACH
LEXENTRY:	SEVENTEEN	17	NUMBER	DETACH
LEXENTRY:	SEVENTEENTH	17TH	WORD,ORD	DETACH
LEXENTRY:	SEVENTH	7TH	WORD,ORD	DETACH
LEXENTRY:	SEVENTIETH	70TH	WORD,ORD	DETACH
LEXENTRY:	SEVENTY	70	NUMBER	DETACH
LEXENTRY:	SHED 	SHED	UNITH	DETACH
LEXENTRY:	SHED	SHED	UNITH	DETACH
LEXENTRY:	SHOP	SHOP	PLACEN,UNITH	DETACH
LEXENTRY:	SHUN	SHUNT	WORD,TYPE	DETACH
LEXENTRY:	SHUNT	SHUNT	WORD,TYPE	DETACH
LEXENTRY:	SITE	SE	UNITH	DETACH
LEXENTRY:	SITE	SITE	UNITH	DETACH
LEXENTRY:	SIX	6	NUMBER	DETACH
LEXENTRY:	SIXTEEN	16	NUMBER	DETACH
LEXENTRY:	SIXTEENTH	16TH	WORD,ORD	DETACH
LEXENTRY:	SIXTH	6TH	WORD,ORD	DETACH
LEXENTRY:	SIXTIETH	60TH	WORD,ORD	DETACH
LEXENTRY:	SIXTY	60	NUMBER	DETACH
LEXENTRY:	SKLN	SKYLINE	WORD,TYPE	DETACH
LEXENTRY:	SKYLINE	SKYLINE	WORD,TYPE	DETACH
LEXENTRY:	SLOPE	SLOPE	WORD,TYPE	DETACH
LEXENTRY:	SLPE	SLOPE	WORD,TYPE	DETACH
LEXENTRY:	SL	SL	UNITH	DETACH
LEXENTRY:	SOUTH AUSTRALIA	SOUTH AUSTRALIA	WORD,PROV	DETACH
LEXENTRY:	SOUTHEAST	SE	DIRECT	DETACH
LEXENTRY:	SOUTH	S	DIRECT	DETACH
LEXENTRY:	SOUTH	SOUTH	WORD,TYPE	DETACH
LEXENTRY:	SOUTHWEST	SW	DIRECT	DETACH
LEXENTRY:	SPUR	SPUR	WORD,TYPE	DETACH
LEXENTRY:	SQ	SQUARE	WORD,TYPE	DETACH
LEXENTRY:	SQUARE	SQ	TYPE	DET_SUF
LEXENTRY:	SQUARE	SQUARE	WORD,TYPE	DETACH
LEXENTRY:	S	S	SINGLE,WORD,DIRECT	DETACH
LEXENTRY:	STADIUM	STADIUM	PLACEN	DETACH
LEXENTRY:	STAI	STRAIT	WORD,TYPE	DETACH
LEXENTRY:	STALL	SL	UNITH	DETACH
LEXENTRY:	STATION	STATION	PLACEN	DETACH
LEXENTRY:	STEPS	STEPS	WORD,TYPE	DETACH
LEXENTRY:	STE	STE	UNITH	DETACH
LEXENTRY:	STH	SOUTH	WORD,TYPE	DETACH
LEXENTRY:	STORE	STORE	PLACEN	DETACH
LEXENTRY:	STPS	STEPS	WORD,TYPE	DETACH
LEXENTRY:	STRAIGHT	STRAIGHT	WORD,TYPE	DETACH
LEXENTRY:	STRAIT	STRAIT	WORD,TYPE	DETACH
LEXENTRY:	STRAND	STRAND	WORD,TYPE	DETACH
LEXENTRY:	STRA	STRAND	WORD,TYPE	DETACH
LEXENTRY:	STREET	STREET	WORD,TYPE	DETACH
LEXENTRY:	STREET	ST	TYPE	DET_SUF
LEXENTRY:	STRIP	STRIP	WORD,TYPE	DETACH
LEXENTRY:	STRP	STRIP	WORD,TYPE	DETACH
LEXENTRY:	STRT	STRAIGHT	WORD,TYPE	DETACH
LEXENTRY:	ST	STREET	WORD,TYPE	DETACH
LEXENTRY:	ST	ST	TYPE,WORD	DETACH,DET_SUF
LEXENTRY:	SUBWAY	SUBWAY	WORD,TYPE	DETACH
LEXENTRY:	SUITE	STE	UNITH	DETACH
LEXENTRY:	SVWY	SERVICEWAY	WORD,TYPE	DETACH
LEXENTRY:	SW	SW	DIRECT	DETACH
LEXENTRY:	TARN	TARN	WORD,TYPE	DETACH
LEXENTRY:	TASMANIA	TASMANIA	WORD,PROV	DETACH
LEXENTRY:	TAS	TAS	WORD,PROV	DETACH
LEXENTRY:	TCE	TCE	TYPE	DET_SUF
LEXENTRY:	TCE	TERRACE	WORD,TYPE	DETACH
LEXENTRY:	TEN	10	NUMBER	DETACH
LEXENTRY:	TENTH	10TH	WORD,ORD	DETACH
LEXENTRY:	TERRACE	TCE	TYPE	DET_SUF
LEXENTRY:	TERRACE	TERRACE	WORD,TYPE	DETACH
LEXENTRY:	THEATER	THEATER	PLACEN	DETACH
LEXENTRY:	THEATRE	THEATRE	PLACEN	DETACH
LEXENTRY:	THFR	THOROUGHFARE	WORD,TYPE	DETACH
LEXENTRY:	THIRD	3RD	WORD,ORD	DETACH
LEXENTRY:	THIRTEEN	13	NUMBER	DETACH
LEXENTRY:	THIRTEENTH	13TH	WORD,ORD	DETACH
LEXENTRY:	THIRTIETH	30TH	WORD,ORD	DETACH
LEXENTRY:	THIRTY	30	NUMBER	DETACH
LEXENTRY:	THOROUGHFARE	THOROUGHFARE	WORD,TYPE	DETACH
LEXENTRY:	THREE	3	NUMBER	DETACH
LEXENTRY:	THROUGHWAY	THROUGHWAY	WORD,TYPE	DETACH
LEXENTRY:	THRU	THROUGHWAY	WORD,TYPE	DETACH
LEXENTRY:	TKWY	TRUNKWAY	WORD,TYPE	DETACH
LEXENTRY:	TLWY	TOLLWAY	WORD,TYPE	DETACH
LEXENTRY:	TMWY	TRAMWAY	WORD,TYPE	DETACH
LEXENTRY:	TOLLWAY	TOLLWAY	WORD,TYPE	DETACH
LEXENTRY:	TOP	TOP	WORD,TYPE	DETACH
LEXENTRY:	TOR	TOR	WORD,TYPE	DETACH
LEXENTRY:	TRACK	TRACK	WORD,TYPE	DETACH
LEXENTRY:	TRAIL	TRAIL	WORD,TYPE	DETACH
LEXENTRY:	TRAMWAY	TRAMWAY	WORD,TYPE	DETACH
LEXENTRY:	TRAVERSE	TRAVERSE	WORD,TYPE	DETACH
LEXENTRY:	TRIANGLE	TRIANGLE	WORD,TYPE	DETACH
LEXENTRY:	TRK	TRACK	WORD,TYPE	DETACH
LEXENTRY:	TRL	TRAIL	WORD,TYPE	DETACH
LEXENTRY:	TRUNKWAY	TRUNKWAY	WORD,TYPE	DETACH
LEXENTRY:	TRUST	TRUST	PLACEN	DETACH
LEXENTRY:	TUNL	TUNNEL	WORD,TYPE	DETACH
LEXENTRY:	TUNNEL	TUNNEL	WORD,TYPE	DETACH
LEXENTRY:	TURN	TURN	WORD,TYPE	DETACH
LEXENTRY:	TVSE	TRAVERSE	WORD,TYPE	DETACH
LEXENTRY:	TWELFTH	12TH	WORD,ORD	DETACH
LEXENTRY:	TWELVE	12	NUMBER	DETACH
LEXENTRY:	TWENTIETH	20TH	WORD,ORD	DETACH
LEXENTRY:	TWENTY	20	NUMBER	DETACH
LEXENTRY:	TWIST	TWIST	WORD,TYPE	DETACH
LEXENTRY:	TWO	2	NUMBER	DETACH
LEXENTRY:	UG	UPPER GROUND FLOOR	UNITH	DETACH
LEXENTRY:	UNDERPASS	UNDERPASS	WORD,TYPE	DETACH
LEXENTRY:	UNIT	U	UNITH	DETACH
LEXENTRY:	UNIVERSITY	UNIVERSITY	PLACEN	DETACH
LEXENTRY:	UPAS	UNDERPASS	WORD,TYPE	DETACH
LEXENTRY:	UPPER GROUND FLOOR	UPPER GROUND FLOOR	UNITH	DETACH
LEXENTRY:	U	U	SINGLE,WORD,UNITH	DETACH
LEXENTRY:	VALE	VALE	WORD,TYPE	DETACH
LEXENTRY:	VALLEY	VALLEY	WORD,TYPE	DETACH
LEXENTRY:	VERGE	VERGE	WORD,TYPE	DETACH
LEXENTRY:	VIADUCT	VIADUCT	WORD,TYPE	DETACH
LEXENTRY:	VIAD	VIADUCT	WORD,TYPE	DETACH
LEXENTRY:	VICTORIA	VICTORIA	WORD,PROV	DETACH
LEXENTRY:	VIC	VIC	WORD,PROV	DETACH
LEXENTRY:	VIEWS	VIEWS	WORD,TYPE	DETACH
LEXENTRY:	VIEW	VIEW	WORD,TYPE	DETACH
LEXENTRY:	VILLAGE	VILLAGE	WORD,TYPE	DETACH
LEXENTRY:	VILLAS	VILLAS	WORD,TYPE	DETACH
LEXENTRY:	VILLA	VILLA	WORD,TYPE	DETACH
LEXENTRY:	VILLA	VLLA	UNITH	DETACH
LEXENTRY:	VISTA	VISTA	WORD,TYPE	DETACH
LEXENTRY:	VLGE	VILLAGE	WORD,TYPE	DETACH
LEXENTRY:	VLLA	VILLA	WORD,TYPE	DETACH
LEXENTRY:	VLLA	VLLA	UNITH	DETACH
LEXENTRY:	VLLS	VILLAS	WORD,TYPE	DETACH
LEXENTRY:	VLLY	VALLEY	WORD,TYPE	DETACH
LEXENTRY:	VSTA	VISTA	WORD,TYPE	DETACH
LEXENTRY:	VUE	VUE	WORD,TYPE	DETACH
LEXENTRY:	VWS	VIEWS	WORD,TYPE	DETACH
LEXENTRY:	WADE	WADE	WORD,TYPE	DETACH
LEXENTRY:	WALK	WALK	WORD,TYPE	DETACH
LEXENTRY:	WALKWAY	WALKWAY	WORD,TYPE	DETACH
LEXENTRY:	WAREHOUSE	WE	UNITH	DETACH
LEXENTRY:	WATERS	WATERS	WORD,TYPE	DETACH
LEXENTRY:	WATERWAY	WATERWAY	WORD,TYPE	DETACH
LEXENTRY:	WA	WA	WORD,PROV	DETACH
LEXENTRY:	WAY	WAY	WORD,TYPE	DETACH
LEXENTRY:	WDS	WOODS	WORD,TYPE	DETACH
LEXENTRY:	WD	WOOD	WORD,TYPE	DETACH
LEXENTRY:	WESTERN AUSTRALIA	WESTERN AUSTRALIA	WORD,PROV	DETACH
LEXENTRY:	WEST	W	DIRECT	DETACH
LEXENTRY:	WEST	WEST	WORD,TYPE	DETACH
LEXENTRY:	WE	WE	UNITH	DETACH
LEXENTRY:	WHARF	WHARF	WORD,TYPE	DETACH
LEXENTRY:	WHRF	WHARF	WORD,TYPE	DETACH
LEXENTRY:	WKWY	WALKWAY	WORD,TYPE	DETACH
LEXENTRY:	WOODS	WOODS	WORD,TYPE	DETACH
LEXENTRY:	WOOD	WOOD	WORD,TYPE	DETACH
LEXENTRY:	WTRS	WATERS	WORD,TYPE	DETACH
LEXENTRY:	WTWY	WATERWAY	WORD,TYPE	DETACH
LEXENTRY:	W	W	SINGLE,WORD,DIRECT	DETACH
LEXENTRY:	WYND	WYND	WORD,TYPE	DETACH
LEXENTRY:	YARD	YARD	WORD,TYPE	DETACH
$$
where countrycode='au' and dataset='gnaf';
update as_config set clexicon = as_compile_lexicon(lexicon) where countrycode='au' and dataset='gnaf';

