#
#  $Id: Makefile.nt,v 1.3 2012-06-03 14:04:53 woodbri Exp $
#
#  $Log: Makefile.nt,v $
#  Revision 1.3  2012-06-03 14:04:53  woodbri
#  Add to help -DALTNAMES option.
#
#  Revision 1.2  2009/01/09 05:14:04  woodbri
#  Added timezone.shp file and removed usps-actual.db from nt which does not need it.
#
#  Revision 1.1  2009/01/09 04:33:28  woodbri
#  Modified Makefile to support targets tar-nt, tar-tgr, tar-all.
#  Added additional Makefile.* specific to tgr or nt releases.
#
#  Revision 1.11  2008/10/09 20:19:28  woodbri
#  Added install target and removed -ldb from the link targets.
#
#  Revision 1.10  2008/09/30 20:30:15  woodbri
#  Fixed a typo in the help target.
#
#  Revision 1.9  2008/09/30 20:14:30  woodbri
#  Added an option to include the FR_SPD_LIM and TO_SPD_LIM from the Streets.deb
#  to the output files.
#
#  Revision 1.8  2008/09/30 18:30:20  woodbri
#  Adding geo-sqlite.c and tgr2rgeo-sqlite.c, updates to Makefile for same.
#  Filter out tileindexes when loading data to pg.
#
#  Revision 1.7  2008/05/15 14:08:24  woodbri
#  Adding load-nt2pg
#
#  Revision 1.6  2008/05/13 18:40:06  woodbri
#  Added optional parameter nt2rgeo-sqlite to allow you to split the output file
#  because the dbf files were getting over 2GB. Added dbname as required argument
#  to rgeo2pg.
#
#  Revision 1.5  2008/04/11 13:51:30  woodbri
#  Updates the make tar target to work.
#
#  Revision 1.4  2008/04/10 15:23:42  woodbri
#  Cleanup files and Makefile.
#
#  Revision 1.3  2008/04/10 14:56:54  woodbri
#  Adding new files based on sqlite as underlying data store.
#
#  Revision 1.2  2008/03/25 18:43:09  woodbri
#  Updated Makefile to add libshp to the include search path
#  Updated nt2rgeo.c to be for libdb4.2 API
#
#  Revision 1.1  2008/02/04 03:38:59  woodbri
#  Updating cvs local changes.
#
#  Revision 2.6  2005/08/20 13:11:26  woodbri
#  Added code to calcuate the area of water polygons and add the value to
#  the dbf attribute file.
#
#  Revision 2.5  2005/02/25 01:06:25  woodbri
#  Changes required to support freeBSD.
#  Removed "libshp/" fromt the #include <shapelib.h>
#  Added -I/usr/local/include in the Makefiles
#
#  Revision 2.4  2005/01/15 13:16:45  woodbri
#  Add header comments.
#  Updated make file so it can be run with dmalloc via:
#  make DMALLOC=1
#
#
#  Revision 1.1  2001/12/04 21:12:18  woodbri
#  Initial revision
#

CC = gcc

DMALLOC_CFLAGS=
DMALLOC_LIBS=
ifdef DMALLOC
DMALLOC_CFLAGS=-DDMALLOC -DDMALLOC_FUNC_CHECK
DMALLOC_LIBS=-ldmalloc
endif
ifdef CYGWIN
DMALLOC_CFLAGS=
DMALLOC_LIBS=
endif

DATE=`date +%Y%m%d`

CFLAGS+=-g -DUNIX
gebug : CFLAGS+=-g -DUNIX $(DMALLOC_CFLAGS)

INCLUDE=-I. -I.. -I /usr/include/libshp -I/home/woodbri/include -I/usr/local/include

LIBS=-lshp -lm
debug : LIBS=-lshp $(DMALLOC_LIBS) -lm

LIBDIRS=-L. -L/home/woodbri/lib -L/usr/lib -L/usr/local/lib

OBJS=nt2rgeo-sqlite.o dbf2sqlite.o 

all:   dbf2sqlite nt2rgeo-sqlite 
opt:   dbf2sqlite nt2rgeo-sqlite 

help:
	@echo 'Usage: [CFLAGS=-DSPEED_LIMIT  -DALTNAMES'] [DMALLOC=1] make clean|tar|all|opt|debug'

.c.o:   Makefile dbf2sqlite.h
	$(CC) $(CFLAGS) -c $(INCLUDE) $<

nt2rgeo-sqlite:    nt2rgeo-sqlite.o dbf2sqlite.o
	$(CC) $(CFLAGS) -o nt2rgeo-sqlite nt2rgeo-sqlite.o dbf2sqlite.o $(INCLUDE) $(LIBDIRS) -lsqlite3 $(LIBS) 

tgr2rgeo-sqlite:    tgr2rgeo-sqlite.o dbf2sqlite.o
	$(CC) $(CFLAGS) -o tgr2rgeo-sqlite tgr2rgeo-sqlite.o dbf2sqlite.o $(INCLUDE) $(LIBDIRS) -lsqlite3 $(LIBS) 

rgeo2geo-sqlite:    rgeo2geo-sqlite.o
	$(CC) $(CFLAGS) -o rgeo2geo-sqlite rgeo2geo-sqlite.o $(INCLUDE) $(LIBDIRS) -lsqlite3 $(LIBS) 

geo-sqlite:    geo-sqlite.o
	$(CC) $(CFLAGS) -o geo-sqlite geo-sqlite.o $(INCLUDE) -Wl,-rpath,/home/woodbri/lib $(LIBDIRS) -lsqlite3 $(LIBS) 

dbf2sqlite:    dbf2sqlite-main.o dbf2sqlite.o
	$(CC) $(CFLAGS) -o dbf2sqlite dbf2sqlite-main.o dbf2sqlite.o $(INCLUDE) $(LIBDIRS) -lsqlite3 $(LIBS) 

tar:
	mkdir -p nt2rgeo-$(DATE)/data
	cat inventory.nt  | xargs --replace={} cp -p {} nt2rgeo-$(DATE)/.
	(cd nt2rgeo-$(DATE) ; ln -s Makefile.nt Makefile)
	cp -p usps-actual.db nt2rgeo-$(DATE)
	cp -fp data/timeznp020.* nt2rgeo-$(DATE)/data
	tar  czf nt2rgeo-$(DATE).tgz nt2rgeo-$(DATE)
	rm -rf nt2rgeo-$(DATE)

clean:
	rm -f *.o tgr2rgeo-sqlite nt2rgeo-sqlite rgeo2geo-sqlite dbf2sqlite core nt2rgeo-sqlite.db tgr2rgeo-sqlite.db geo-sqlite
	
install:
	cp nt2rgeo-sqlite dbf2sqlite  ~/bin
