#!/bin/bash

YEAR=2017
DBPORT=5434
DBNAME=tiger${YEAR}_geo
DBUSER=postgres
DBHOST=localhost

cd ~/dev/navteq
./process-build-places tiger${YEAR}-places.db /u/srcdata/TIGER${YEAR}/
./process-tgr2pagc-2011-shp /u/data/tiger${YEAR}-geo/ /u/srcdata/TIGER${YEAR}/ . &> tiger${YEAR}-geo.log

./load-tiger-geo tiger${YEAR}_geo ${DBPORT} ${YEAR} /u/data/tiger${YEAR}-geo/ &> tiger${YEAR}-geo-load.log

psql -U $DBUSER -h $DBHOST -p $DBPORT tiger${YEAR}_geo -f tiger-geo/us-gaz.sql
psql -U $DBUSER -h $DBHOST -p $DBPORT tiger${YEAR}_geo -f tiger-geo/us-lex.sql
psql -U $DBUSER -h $DBHOST -p $DBPORT tiger${YEAR}_geo -f tiger-geo/us-rules.sql


